(defproject repo-download "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :plugins [[lein-cljsbuild "1.1.3"]
            [lein-ring "0.8.7"]
            [lein-figwheel "0.5.0-6"]]
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.8.34"]
                 [org.clojure/core.async "0.2.374"]
                 [com.twitter/carbonite "1.4.0"]
                 [com.taoensso/timbre "4.3.1"]
                 [dire "0.5.4"]
                 [robert/hooke "1.3.0"]
                 [environ "1.0.3"]
                 [org.clojure/tools.cli "0.3.5"]
                 [clj-time "0.11.0"]
                 [honeysql "0.6.3"]
                 [korma "0.3.2"]
                 [mysql/mysql-connector-java "5.1.31"]
                 [garden "1.3.2"]
                 [hiccup "1.0.5"]
                 [clj-yaml "0.4.0"]
                 [compojure "1.5.0"]
                 [ring "1.4.0"]
                 [ring/ring-defaults "0.2.0"]
                 [org.omcljs/om "0.8.8"]
                 [prismatic/om-tools "0.4.0"]
                 [sablono "0.3.6"]
                 [com.keminglabs/c2 "0.2.3"]
                 [clj-http "3.1.0"]
                 [enlive "1.1.6"]
                 [com.velisco/clj-ftp "0.3.5"]
                 [clj-ssh "0.5.14"]
                 [dk.ative/docjure "1.10.0"]
                 [cheshire "5.6.1"]
                 [org.clojure/data.csv "0.1.3"]
                 [instaparse "1.4.2"]
                 [com.draines/postal "1.11.3"]
                 [com.rpl/specter "0.10.0"]
                 [org.clojure/java.jdbc "0.6.1"]
                 [zookeeper-clj "0.9.4"]
                 [cascalog/cascalog-core "3.0.0"]
                 [clojurewerkz/quartzite "2.0.0"]
                 [clojurewerkz/elastisch "2.2.1"]
                 [org.apache.thrift/libthrift "0.9.3"]
                 [thrift-clj "0.3.0"]
                 [org.apache.storm/storm-core "1.0.0"]
                 [org.apache.storm/storm-hbase "1.0.0"]
                 [com.taoensso/carmine "2.12.2"]
                 [org.apache.storm/storm-redis "1.0.0"]
                 [clj-kafka "0.3.4"]
                 [org.apache.storm/storm-kafka "1.0.0"]])
